Add controllers
MikhailKuznets/java-shareit pull request #1
Opened 2022-12-03 11:42 UTC by MikhailKuznets

2022-12-04 17:43 UTC, andrew-larkin requested changes
Привет! Работа отличная, всего в одном месте требуется скорректировать, а также есть 2 рекомендации, если выполнишь их здесь - будет здорово. Комментарии написаны в одном месте, но относятся ко всем контроллерам/сервисам.

2022-12-04 17:43 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemDto createItem(@RequestHeader("X-Sharer-User-Id") @Positive Long userId,
в реальных проектах ответы контроллера часто оборачивают в класс ResponseEntity, который возвращает не только json, но и http-статус, рекомендую попробовать.

2022-12-04 17:43 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +public class ItemMapper {
рекомендую познакомиться с маленькой библиотекой mapStruct - она позволяет создавать мапперы в одну строчку

2022-12-04 17:43 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    Optional<ItemDto> getItemById(Long itemId);
в ответе сервиса лучше возвращать уже готовый dto, без оболочек типа Optional

2022-12-05 15:59 UTC, MikhailKuznets commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    Optional<ItemDto> getItemById(Long itemId);
Поправил

2022-12-05 16:00 UTC, MikhailKuznets commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemDto createItem(@RequestHeader("X-Sharer-User-Id") @Positive Long userId,
Познакомил проект с ResponseEntity

2022-12-20 16:10 UTC, merged