Add bookings
MikhailKuznets/java-shareit pull request #2
Opened 2022-12-29 19:22 UTC by MikhailKuznets

Добавлен функционал бронирования предметов и добавление комментариев.

2022-12-30 19:42 UTC, andrew-larkin requested changes
Привет! Очень хорошо, небольшой рефакторинг и работа будет принята.

2022-12-30 19:42 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    Booking findFirstByItem_IdAndEndIsBeforeOrderByEndDesc(Long itemId, LocalDateTime now);
голый объект не стоит возвращать, т.к. если ничего не найдется, мы получим null. Здесь лучшим решением будет использовать класс-обертку Optional, а в сервисе получать Booking с помощью метода .orElseThrow

2022-12-30 19:42 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        User owner = booking.getItem().getOwner();
когда мы заходим на третий уровень в методах, желательно делать проверку на null, чтобы не схватить NPE

2022-12-30 19:42 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    @Query(" select i from Item i " +
очень хорошо!

2022-12-30 19:42 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +@Deprecated
мне кажется, можно удалить, насколько я помню, он нам больше не понадобится

2022-12-30 19:42 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
>      public void deleteUserById(@PathVariable @Positive Long userId) {
вот здесь тоже можно использовать ResponseEntity - в квадратные скобки добавить спец класс Void

2022-12-31 22:36 UTC, MikhailKuznets commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
>      public void deleteUserById(@PathVariable @Positive Long userId) {
Спасибо за идею. Попробовал использовать.

2022-12-31 22:46 UTC, MikhailKuznets commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    Booking findFirstByItem_IdAndEndIsBeforeOrderByEndDesc(Long itemId, LocalDateTime now);
Использовал .orElseThrow в других местах программы. Но если я правильно понял именно здесь **null** возвращать допустимо) 
Кажется тесты Postman, например _bokings/Item 2 get by user1 without  bookings_ ожидают **null**:

> pm.test("Status code is 200", function () {
>     pm.expect(pm.response.code).to.be.oneOf([200]);
> });
> pm.test("Item 2 get by user1 without  bookings", function () {
>     var jsonData = pm.response.json();
>     pm.expect(jsonData.id, '"id" field').to.eql(2);
>     pm.expect(jsonData.name, '"name" field').to.eql('Отвертка');
>     pm.expect(jsonData.description, '"description" field').to.eql('Аккумуляторная отвертка');
>     pm.expect(jsonData.available, '"available" field').to.true;
>     **pm.expect(jsonData.lastBooking, '"lastBooking" field').null**;
>     **pm.expect(jsonData.nextBooking, '"nextBooking" field').null**;
> });

2022-12-31 23:11 UTC, MikhailKuznets commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        User owner = booking.getItem().getOwner();
Добавил проверку на **null**
Правильно я понял, что:
1й уровень - экземпляр Booking booking
2й уровень - booking.getItem()
3й уровень - booking.getItem().getOwner() ?

2023-01-01 10:16 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        User owner = booking.getItem().getOwner();
Да

2023-01-03 10:49 UTC, merged